databases:
  - name: knubot
    databaseName: knubot
    user: knubot
    region: singapore

services:
  - type: web
    name: knubot
    runtime: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn knubot.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: knubot
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4