# Generated by Django 4.2.7 on 2023-12-05 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("links", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="link",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="link",
            name="owner",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
